<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="laser_radius" value="0.1" />
    <xacro:property name="laser_length" value="0.08" />
    <xacro:property name="laser_z_offset" value="0.2" />

    <link name="base_scan">
        <inertial>
            <mass value="0.2" />
            <origin rpy="0 0 0" xyz="0 0 0" />
            <inertia ixx="0.0006066666666666668" ixy="0" ixz="0" iyy="0.0006066666666666668" iyz="0"
                izz="0.0010000000000000002" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}" />
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_scan" />
        <origin rpy="0 0 0" xyz="${base_length/2 + laser_radius} 0 ${laser_z_offset}" />
    </joint>

    <gazebo reference="base_scan">
        <material>Gazebo/FlatBlack</material>
        <sensor name="head_hokuyo_sensor_0" type="ray">
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>100</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1.000000</resolution>
                        <min_angle>-1.785</min_angle>
                        <max_angle>1.785</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.120000</min>
                    <max>12.0</max>
                    <resolution>0.010</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="ray_controller"
                filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=/scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>base_scan</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>