<?xml version="1.0"?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from
/home/alper/Mobile_Robot_URDF_Maker/install/mobRobURDF_description/share/mobRobURDF_description/urdf/temp/4_wheeled/via.xacro
| -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="via"
  xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Base Link -->
  <link name="base_footprint" />
  <!-- <xacro:include filename="$(find
  mobRobURDF_description)/urdf/gazebo_files/gazebo_sensors.xacro" /> -->

  <xacro:include filename="common_properties.xacro" />

  <xacro:property name="base_length" value="2.63" />
  <xacro:property name="base_width" value="1.26" />
  <xacro:property name="base_height" value="0.928" />

  <xacro:property name="base_radius" value="0.25" />
  <xacro:property name="wheel_length" value="0.12" />
  <xacro:property name="front_wheel_x_offset" value="0.6775" />
  <xacro:property name="rear_wheel_x_offset" value="0.82" />
  <xacro:property name="wheel_z_offset" value="0.1" />

  <link name="base_link">
    <inertial>
      <mass value="1500" />
      <origin rpy="0 0 0" xyz="0 0 ${base_height/2}" />
      <inertia ixx="1997.86" ixy="-3e-05" ixz="-1e-06" iyy="442.769" iyz="62.5206"
        izz="2238.05" />
    </inertial>
    <visual>
      <origin rpy="0 0 1.57" xyz="0 0 ${base_height/2}" />
      <geometry>
        <mesh filename="package://via_description/meshes/via_chassis.dae" />
      </geometry>
      <material name="Gray" />
    </visual>
    <collision>
      <origin rpy="0 0 1.57" xyz="0 0 ${base_height/2}" />
      <geometry>
        <mesh filename="package://via_description/meshes/via_chassis.dae" />
      </geometry>
    </collision>
  </link>

    <link name="rear_right_axle">
        <visual>
            <geometry>
                <mesh filename="package://via_description/meshes/tire.dae" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </visual>
        <xacro:cylinder_inertia m="30" r="${base_radius*2}" l="${wheel_length}"
            xyz="0 0 0" rpy="${pi / 2.0} 0 0" />

        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
    </link>

    <link name="rear_left_axle">
        <visual>
            <geometry>
                <mesh filename="package://via_description/meshes/tire.dae" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </visual>
        <xacro:cylinder_inertia m="30" r="${base_radius*2}" l="${wheel_length}"
            xyz="0 0 0" rpy="${pi / 2.0} 0 0" />

        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
    </link>

    <link name="front_right_steer">
        <inertial>
            <origin rpy="0 0 0" xyz="0.003381 1.5929e-07 0.02162" />
            <mass value="1" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>

    <link name="front_right_axle">
        <visual>
            <geometry>
                <mesh filename="package://via_description/meshes/tire.dae" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </visual>
        <xacro:cylinder_inertia m="30" r="${base_radius*2}" l="${wheel_length}"
            xyz="0 0 0" rpy="${pi / 2.0} 0 0" />

        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
    </link>

    <link name="front_left_steer">
        <inertial>
            <origin rpy="0 0 0" xyz="0.003381 1.5929e-07 0.02162" />
            <mass value="1" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>

    <link name="front_left_axle">
        <visual>
            <geometry>
                <mesh filename="package://via_description/meshes/tire.dae" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </visual>

        <xacro:cylinder_inertia m="30" r="${base_radius*2}" l="${wheel_length}"
            xyz="0 0 0" rpy="${pi / 2.0} 0 0" />

        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${base_radius-wheel_z_offset}" rpy="0 0 0" />
    </joint>

    <joint name="rear_right_axle_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_axle" />
        <origin
            xyz="${-rear_wheel_x_offset} ${-(base_width / 2.0) + (wheel_length / 2.0)} ${wheel_z_offset}"
            rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="rear_left_axle_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_axle" />
        <origin
            xyz="${-rear_wheel_x_offset} ${(base_width / 2.0) - (wheel_length / 2.0)} ${wheel_z_offset}"
            rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="front_right_steer_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_steer" />
        <origin
            xyz="${front_wheel_x_offset} ${-(base_width / 2.0) + (wheel_length / 2.0)} ${wheel_z_offset}"
            rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="front_right_axle_joint" type="continuous">
        <parent link="front_right_steer" />
        <child link="front_right_axle" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="front_left_steer_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_steer" />
        <origin
            xyz="${front_wheel_x_offset} ${(base_width / 2.0) - (wheel_length / 2.0)} ${wheel_z_offset}"
            rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="front_left_axle_joint" type="continuous">
        <parent link="front_left_steer" />
        <child link="front_left_axle" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

  <!-- <xacro:include filename="ray.xacro" />
  <xacro:include filename="camera.xacro" />
  <xacro:include filename="imu.xacro" />
  <xacro:include filename="gps.xacro" />
  <xacro:include filename="distance.xacro" /> -->
  <xacro:include filename="via_gazebo.xacro" />

</robot>